---
apiVersion: v1
kind: Namespace
metadata:
  name: tickets-prod
  labels:
    name: tickets-prod
    environment: prod
    project: aegistickets

---
apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: tickets-prod
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: tickets-prod
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "6Gi"
    limits.cpu: "8"
    limits.memory: "12Gi"
    pods: "30"
    services.loadbalancers: "2"
    persistentvolumeclaims: "10"
