# Dev environment values for frontend
image:
  repository: 455921291596.dkr.ecr.eu-west-1.amazonaws.com/aegistickets-lite/frontend
  tag: "sha-5dffe2e"

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
