# Dev environment values for frontend
image:
  repository: <ACCOUNT_ID>.dkr.ecr.eu-west-1.amazonaws.com/aegistickets-lite/frontend
  tag: "sha-<GIT_SHA>"

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
