# Prod environment values for backend
image:
  repository: <ACCOUNT_ID>.dkr.ecr.eu-west-1.amazonaws.com/aegistickets-lite/backend
  tag: "sha-<GIT_SHA>"

replicaCount: 3

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
