name: DAST with OWASP ZAP

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL for DAST scan'
        required: true
        default: 'http://YOUR-ALB-DNS.eu-west-1.elb.amazonaws.com'

permissions:
  contents: read
  security-events: write

jobs:
  zap-scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: ${{ github.event.inputs.target_url }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: zap-report
          path: report_html.html

      - name: Create SARIF from ZAP
        if: always()
        run: |
          # Convert ZAP JSON to SARIF if available
          echo "ZAP scan completed. Check artifacts for detailed report."

      - name: Summary
        if: always()
        run: |
          echo "### DAST Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Target:** ${{ github.event.inputs.target_url }}" >> $GITHUB_STEP_SUMMARY
          echo "**Scan Type:** ZAP Baseline" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Download the full report from the workflow artifacts." >> $GITHUB_STEP_SUMMARY
